### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by swanseahost** [ahmyi/cryptonote-stellite-pool#2]
miner@etn:~/cryptonote-stellite-pool$ node init.js
Failed to read config file config.json

SyntaxError: Unexpected token /

/home/miner/cryptonote-stellite-pool/lib/logger.js:16
var logDir = config.logging.files.directory;
             ^
ReferenceError: config is not defined
    at Object.<anonymous> (/home/miner/cryptonote-stellite-pool/lib/logger.js:16:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/miner/cryptonote-stellite-pool/init.js:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
miner@etn:~/cryptonote-stellite-pool$

**Comment by ahmyi** [comment]
The config.json has a problem..will upload new one

**Comment by ahmyi** [comment]
Please refer to latest commit #4 config.default.json
